# Exercicio 2

¿Cuán rápido puedes ordenar estos
productos?

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [182]:
df = pd.read_csv('ordenamiento.csv')

In [3]:
df.head()

item_id      vertical              category                   domain  \
0  512208310           CPG             PETS FOOD  MLC-CATS_AND_DOGS_FOODS   
1  468513076            CE           ELECTRONICS               MLC-RANGES   
2  614337410            CE           ELECTRONICS       MLC-SMART_SPEAKERS   
3  634351318  APP & SPORTS               APPAREL                MLC-PANTS   
4  528383704           ACC  VEHICULAR MULTIMEDIA                  MLC-GPS   

    score  
0  0.0272  
1  0.9256  
2  0.8304  
3  0.0560  
4  0.2334

In [4]:
df[1::]

item_id         vertical              category  \
1     468513076               CE           ELECTRONICS   
2     614337410               CE           ELECTRONICS   
3     634351318     APP & SPORTS               APPAREL   
4     528383704              ACC  VEHICULAR MULTIMEDIA   
5     507642148  HOME & INDUSTRY            HOME&DECOR   
...         ...              ...                   ...   
4995  621100365  HOME & INDUSTRY            HOME&DECOR   
4996  613555182  BEAUTY & HEALTH         PHARMACEUTICS   
4997  535350054  HOME & INDUSTRY            STATIONARY   
4998  549193472  HOME & INDUSTRY            HOME&DECOR   
4999  580229494               CE           ELECTRONICS   

                              domain   score  
1                         MLC-RANGES  0.9256  
2                 MLC-SMART_SPEAKERS  0.8304  
3                          MLC-PANTS  0.0560  
4                            MLC-GPS  0.2334  
5                         MLC-STOOLS  0.3796  
...                              ...     ...  
4995      MLC-HOME_LIGHTING_SUPPLIES  0.8520  
4996  MLC-HUMIDIFIERS_AND_VAPORIZERS  0.9298  
4997                MLC-PENCIL_CASES  0.7832  
4998            MLC-CHRISTMAS_LIGHTS  0.2830  
4999                 MLC-HAIR_DRYERS  0.1456  

[4999 rows x 5 columns]

In [5]:
test = df.query('item_id.isin([641416750,512208310,468513076,614337410,634351318,22351223])')

In [8]:
l = [1,2,3,8]

In [10]:
l[1:1] = [10]

In [20]:
l

[1, 10, 2, 3, 8]

In [33]:
l = np.array(l)

In [34]:
l

array([ 1, 10,  2,  3,  8])

In [40]:
l = np.insert(l,2,100)

In [62]:
l

array([  1,  10, 100,   2,   3,   8])

In [63]:
np.insert(l,2,[98,99])

array([  1,  10,  98,  99, 100,   2,   3,   8])

In [57]:
abs(l-9)

array([ 8,  1, 91,  7,  6,  1])

In [61]:
~np.isin(abs(l-9),l)

array([False, False,  True,  True,  True, False])

In [52]:
np.argmin(abs(l-9))

1

In [23]:
df.index.to_numpy()

array([   1,    2,    3, ..., 4998, 4999, 5000], dtype=int64)

In [83]:
df[df['item_id']==22351223].empty

True

In [101]:
(df.loc[4997::,'vertical']=='CE') & True

4997    False
4998    False
4999     True
Name: vertical, dtype: bool

In [213]:
def order_dataframe_test(df):
    df = df.sort_values('score', ascending=False).reset_index(drop=True)
    index = df.index.to_numpy()
    items_ids = df['item_id'].to_list()
    indexes_locked = [2,3]
    
    mask_locked = np.ones( df.shape[0], dtype=bool)
    
    for i in indexes_locked:
        mask_locked[i] = False
    print(mask_locked)
    vertical_counter = 0
    domain_counter = 0
    last_vertical = None
    last_domain = None
    for i in range(0,len(index)):
        if i not in indexes_locked:
            idx = index[i]
            mask = True
            row = df.loc[idx] 
            if row['vertical'] == last_vertical:
                vertical_counter += 1
            else:
                vertical_counter = 0
            if row['domain'] == last_domain:
                domain_counter += 1
            else:
                domain_counter = 0

            if vertical_counter==1:
                mask = mask & (df.iloc[i::]['vertical'] != last_vertical) & mask_locked[i::]
            if domain_counter==4:
                mask = mask & (df.iloc[i::]['domain'] != last_domain) & mask_locked[i::]

            if isinstance(mask, pd.Series):
                new_idx = df.iloc[i::][mask].iloc[0].name
                index = index[index != new_idx]
                index = np.insert(index,i,new_idx)
                idx = new_idx

            last_vertical = df.loc[idx,'vertical']
            last_domain = df.loc[idx,'domain']
            df = df.reindex(index)
    return df.reindex(index)

In [209]:
test.sort_values('score', ascending=False).reset_index(drop=True)

item_id      vertical     category                   domain   score
0  641416750            CE       MOBILE           MLC-CELLPHONES  0.9986
1  468513076            CE  ELECTRONICS               MLC-RANGES  0.9256
2  614337410            CE  ELECTRONICS       MLC-SMART_SPEAKERS  0.8304
3  634351318  APP & SPORTS      APPAREL                MLC-PANTS  0.0560
4  512208310           CPG    PETS FOOD  MLC-CATS_AND_DOGS_FOODS  0.0272

In [214]:
order_dataframe_test(test)

[ True  True False False  True]


item_id      vertical     category                   domain   score
0  641416750            CE       MOBILE           MLC-CELLPHONES  0.9986
4  512208310           CPG    PETS FOOD  MLC-CATS_AND_DOGS_FOODS  0.0272
1  468513076            CE  ELECTRONICS               MLC-RANGES  0.9256
2  614337410            CE  ELECTRONICS       MLC-SMART_SPEAKERS  0.8304
3  634351318  APP & SPORTS      APPAREL                MLC-PANTS  0.0560

In [184]:
order_dataframe_test(df).head(15)

item_id         vertical                category  \
0   590602034               CE             ELECTRONICS   
11  523534468  BEAUTY & HEALTH           PHARMACEUTICS   
1   609438042               CE             ELECTRONICS   
15  541283090  HOME & INDUSTRY  TOOLS AND CONSTRUCTION   
2   634352041               CE                  MOBILE   
19  610865341  HOME & INDUSTRY                INDUSTRY   
3   615879515               CE                  MOBILE   
27  631987792  HOME & INDUSTRY  TOOLS AND CONSTRUCTION   
4   631654974               CE                  MOBILE   
28  514547899  HOME & INDUSTRY  TOOLS AND CONSTRUCTION   
5   908510601               CE                  MOBILE   
40  530533595  HOME & INDUSTRY  TOOLS AND CONSTRUCTION   
6   641416750               CE                  MOBILE   
47  547284733  HOME & INDUSTRY              STATIONARY   
7   587879197               CE             ELECTRONICS   

                               domain   score  
0                   MLC-GAME_CONSOLES  0.9998  
11  MLC-SURGICAL_AND_INDUSTRIAL_MASKS  0.9976  
1                   MLC-GAME_CONSOLES  0.9996  
15                MLC-ELECTRIC_DRILLS  0.9968  
2                      MLC-CELLPHONES  0.9994  
19            MLC-POINTS_OF_SALE_KITS  0.9960  
3                      MLC-CELLPHONES  0.9992  
27               MLC-WELDING_MACHINES  0.9944  
4                      MLC-CELLPHONES  0.9990  
28                MLC-ELECTRIC_DRILLS  0.9942  
5                      MLC-CELLPHONES  0.9988  
40                MLC-ELECTRIC_DRILLS  0.9918  
6                      MLC-CELLPHONES  0.9986  
47                MLC-SCREEN_PRINTERS  0.9904  
7                   MLC-GAME_CONSOLES  0.9984

In [185]:
df.head(15)

item_id         vertical                category  \
0   512208310              CPG               PETS FOOD   
1   468513076               CE             ELECTRONICS   
2   614337410               CE             ELECTRONICS   
3   634351318     APP & SPORTS                 APPAREL   
4   528383704              ACC    VEHICULAR MULTIMEDIA   
5   507642148  HOME & INDUSTRY              HOME&DECOR   
6   521057099  HOME & INDUSTRY              HOME&DECOR   
7   529123507               CE             ELECTRONICS   
8   630745490  HOME & INDUSTRY              HOME&DECOR   
9   627255896              ACC               AUTOPARTS   
10  900724780               CE               COMPUTERS   
11  606285134               CE               COMPUTERS   
12  569066324  HOME & INDUSTRY                INDUSTRY   
13  607191292  HOME & INDUSTRY  TOOLS AND CONSTRUCTION   
14  520012966  HOME & INDUSTRY  TOOLS AND CONSTRUCTION   

                            domain   score  
0          MLC-CATS_AND_DOGS_FOODS  0.0272  
1                       MLC-RANGES  0.9256  
2               MLC-SMART_SPEAKERS  0.8304  
3                        MLC-PANTS  0.0560  
4                          MLC-GPS  0.2334  
5                       MLC-STOOLS  0.3796  
6         MLC-QUILTS_AND_COVERLETS  0.4352  
7                     MLC-BLENDERS  0.2476  
8                   MLC-CORKSCREWS  0.6292  
9   MLC-VEHICLE_MULTIMEDIA_SYSTEMS  0.1804  
10                    MLC-SPEAKERS  0.7818  
11                  MLC-HEADPHONES  0.9586  
12               MLC-OFFICE_CHAIRS  0.0222  
13   MLC-ELECTRIC_PRESSURE_WASHERS  0.9788  
14          MLC-COMBINED_TOOL_SETS  0.8042

In [218]:
def order_dataframe(df):
    df = df.sort_values('score', ascending=False).reset_index(drop=True)
    index = df.index.to_numpy()
    items_ids = df['item_id'].to_list()
    indexes_locked = []
    
    # Rules 1 and 2
    vertical_counter = 0
    domain_counter = 0
    last_vertical = None
    last_domain = None
    for i in range(0,len(index)):
        idx = index[i]
        mask = True
        swap_sku_flag = False
        row = df.loc[idx] 
        if row['vertical'] == last_vertical:
            vertical_counter += 1
        else:
            vertical_counter = 0
        if row['domain'] == last_domain:
            domain_counter += 1
        else:
            domain_counter = 0
        
        if vertical_counter==1:
            mask = mask & (df.iloc[i::]['vertical'] != last_vertical)
            # swap_sku_flag = True
        if domain_counter==4:
            mask = mask & (df.iloc[i::]['domain'] != last_domain)
            # swap_sku_flag = True
            
        if isinstance(mask, pd.Series):
            new_idx = df.iloc[i::][mask].iloc[0].name
            index = index[index != new_idx]
            index = np.insert(index,i,new_idx)
            idx = new_idx
        
        last_vertical = df.loc[idx,'vertical']
        last_domain = df.loc[idx,'domain']
        df = df.reindex(index)
        
    df = df.reset_index(drop=True)
    index = df.index.to_numpy()
    # Rule 3
    if 641416750 in items_ids:
        idx = df[df['item_id']==641416750].index[0]
        indexes_locked.append(2)
        # index.remove(idx)
        index = index[index != idx]
        index = np.insert(index,2,idx)
        # index[2:2] = [idx]
        # temp = index[2]
        # index[2] = idx
        # index.append(temp)
    # Rule 4
    if 22351223 in items_ids:
        idx = df[df['item_id']==22351223].index[0]
        indexes_locked.append(5)
        # index.remove(idx)
        index = index[index != idx]
        index = np.insert(index,5,idx)
        # index[5:5] = [idx]
        # temp = index[5]
        # index[5] = idx
        # index.append(temp)
    # Rule 5
    # Search for the closest sku in the sorted dataframe to fill 9,10,11 positions
    df = df.reindex(index).reset_index(drop=True)
    index = df.index.to_numpy()
    
    indexes_home_decor = df.query("category=='HOME&DECOR'").index.to_numpy()
    indexes_rule5 = np.array([el for el in indexes_home_decor if el not in indexes_locked])
    indexes_to_insert = []
    # Search for the to the closest HOME&DECOR item for each position
    for i in range(8,11):
        # Calculate distances
        distances = abs(indexes_rule5-i)
        index_min_distance = indexes_rule5[np.argmin(distances)]
        indexes_to_insert.append(index_min_distance)
        # Remove index from the eligible rule 5 list
        indexes_rule5 = indexes_rule5[indexes_rule5!=index_min_distance]
        
    remove_mask = ~np.isin(index, indexes_to_insert)
    index = index[remove_mask]
    index = np.insert(index,8,indexes_to_insert)
    indexes_locked.append([8,9,10])
        
    
#     # indexes_rule5
#     # for
#     # temp = df.iloc[8::].query("category=='HOME&DECOR'").head(3)
#     # idxs = temp.index.to_list()
#     # indexes_locked.append([8,9,10])
#     # # Removing indexes 
#     # index = [i for i in index if (i not in idxs)]
    
#     #achar maneira de adicionar items removidos ao fim do item 11

    
#     # pegar as 3 melhores Home e deco para as posicoes 9,10 e 11
#     # olhar linha por linha e observar regras 1 e 2
    
        
    return df.reindex(index)

In [193]:
df_treated = order_dataframe(df)

In [194]:
df_treated.head(15)

item_id         vertical                category  \
0   590602034               CE             ELECTRONICS   
1   523534468  BEAUTY & HEALTH           PHARMACEUTICS   
12  641416750               CE                  MOBILE   
2   609438042               CE             ELECTRONICS   
3   541283090  HOME & INDUSTRY  TOOLS AND CONSTRUCTION   
4   634352041               CE                  MOBILE   
5   610865341  HOME & INDUSTRY                INDUSTRY   
6   615879515               CE                  MOBILE   
7   631987792  HOME & INDUSTRY  TOOLS AND CONSTRUCTION   
8   631654974               CE                  MOBILE   
9   514547899  HOME & INDUSTRY  TOOLS AND CONSTRUCTION   
10  908510601               CE                  MOBILE   
11  530533595  HOME & INDUSTRY  TOOLS AND CONSTRUCTION   
13  547284733  HOME & INDUSTRY              STATIONARY   
14  587879197               CE             ELECTRONICS   

                               domain   score  
0                   MLC-GAME_CONSOLES  0.9998  
1   MLC-SURGICAL_AND_INDUSTRIAL_MASKS  0.9976  
12                     MLC-CELLPHONES  0.9986  
2                   MLC-GAME_CONSOLES  0.9996  
3                 MLC-ELECTRIC_DRILLS  0.9968  
4                      MLC-CELLPHONES  0.9994  
5             MLC-POINTS_OF_SALE_KITS  0.9960  
6                      MLC-CELLPHONES  0.9992  
7                MLC-WELDING_MACHINES  0.9944  
8                      MLC-CELLPHONES  0.9990  
9                 MLC-ELECTRIC_DRILLS  0.9942  
10                     MLC-CELLPHONES  0.9988  
11                MLC-ELECTRIC_DRILLS  0.9918  
13                MLC-SCREEN_PRINTERS  0.9904  
14                  MLC-GAME_CONSOLES  0.9984

In [220]:
order_dataframe(df).tail(15)

item_id         vertical                category  \
4985  529123787  BEAUTY & HEALTH           PHARMACEUTICS   
4986  541133225               CE             ELECTRONICS   
4987  916724092     APP & SPORTS                  SPORTS   
4988  437789846  HOME & INDUSTRY              HOME&DECOR   
4989  539314175              CPG                CLEANING   
4990  908749908  HOME & INDUSTRY  TOOLS AND CONSTRUCTION   
4991  622450210     APP & SPORTS                  SPORTS   
4992  590799374  HOME & INDUSTRY              HOME&DECOR   
4993  539428631              CPG                   FOODS   
4994  620751080  HOME & INDUSTRY              HOME&DECOR   
4995  489295848     APP & SPORTS                 APPAREL   
4996  519320176  HOME & INDUSTRY  TOOLS AND CONSTRUCTION   
4997  489817797              CPG        PERSONAL HYGIENE   
4998  911699995  HOME & INDUSTRY  TOOLS AND CONSTRUCTION   
4999  626161550  BEAUTY & HEALTH           PHARMACEUTICS   

                                  domain   score  
4985   MLC-SURGICAL_AND_INDUSTRIAL_MASKS  0.0028  
4986  MLC-DIGITAL_PORTABLE_MEDIA_PLAYERS  0.0026  
4987   MLC-CAMPING_AND_FISHING_EQUIPMENT  0.0024  
4988                      MLC-BED_SHEETS  0.0022  
4989              MLC-LAUNDRY_DETERGENTS  0.0018  
4990                   MLC-HAMMER_DRILLS  0.0020  
4991         MLC-AEROBIC_CRUNCH_MACHINES  0.0010  
4992             MLC-ELECTRIC_LUNCHBOXES  0.0016  
4993                   MLC-EDIBLE_PAPERS  0.0006  
4994                    MLC-FLOOD_LIGHTS  0.0014  
4995                           MLC-PANTS  0.0004  
4996                MLC-ELECTRIC_BLOWERS  0.0012  
4997                  MLC-WET_BABY_WIPES  0.0002  
4998       MLC-ELECTRIC_PRESSURE_WASHERS  0.0008  
4999   MLC-SURGICAL_AND_INDUSTRIAL_MASKS  0.0000

In [215]:
df.sort_values('score', ascending=False).reset_index(drop=True).head(15)

item_id         vertical       category  \
0   590602034               CE    ELECTRONICS   
1   609438042               CE    ELECTRONICS   
2   634352041               CE         MOBILE   
3   615879515               CE         MOBILE   
4   631654974               CE         MOBILE   
5   908510601               CE         MOBILE   
6   641416750               CE         MOBILE   
7   587879197               CE    ELECTRONICS   
8   619600539               CE      COMPUTERS   
9   615879553               CE         MOBILE   
10  620358521               CE      COMPUTERS   
11  523534468  BEAUTY & HEALTH  PHARMACEUTICS   
12  622127095               CE         MOBILE   
13  908530330               CE         MOBILE   
14  914570948               CE      COMPUTERS   

                               domain   score  
0                   MLC-GAME_CONSOLES  0.9998  
1                   MLC-GAME_CONSOLES  0.9996  
2                      MLC-CELLPHONES  0.9994  
3                      MLC-CELLPHONES  0.9992  
4                      MLC-CELLPHONES  0.9990  
5                      MLC-CELLPHONES  0.9988  
6                      MLC-CELLPHONES  0.9986  
7                   MLC-GAME_CONSOLES  0.9984  
8                       MLC-NOTEBOOKS  0.9982  
9                      MLC-CELLPHONES  0.9980  
10                      MLC-NOTEBOOKS  0.9978  
11  MLC-SURGICAL_AND_INDUSTRIAL_MASKS  0.9976  
12                     MLC-CELLPHONES  0.9974  
13                     MLC-CELLPHONES  0.9972  
14                      MLC-NOTEBOOKS  0.9970

In [217]:
df.sort_values('score', ascending=False).reset_index(drop=True).query('item_id==530533595')

item_id         vertical                category               domain  \
40  530533595  HOME & INDUSTRY  TOOLS AND CONSTRUCTION  MLC-ELECTRIC_DRILLS   

     score  
40  0.9918